apiVersion: v1
kind: Service
metadata:
  name: patient-booking-service
spec:
  selector:
    app: patient-booking
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
