- name: Deploy Flask Appointment Booking App on Kubernetes
  hosts: webserver
  become: false
  tasks:

    - name: Ensure k8s manifests directory exists
      file:
        path: /tmp/k8s
        state: directory

    - name: Copy Kubernetes manifests
      copy:
        src: "{{ playbook_dir }}/../k8s/"
        dest: /tmp/k8s/
        mode: "0644"

    - name: Apply Deployment manifest
      shell: kubectl apply -f /tmp/k8s/deployment.yaml
      register: deploy_result

    - name: Show Deployment result
      debug:
        var: deploy_result.stdout

    - name: Apply Service manifest
      shell: kubectl apply -f /tmp/k8s/service.yaml
      register: service_result

    - name: Show Service result
      debug:
        var: service_result.stdout
